# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: nuget
    directory: /source/ApplyDBMigrationsApp
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /source/Api
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /source/Application
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /source/ArchitectureTests
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /source/CimMessageAdapter
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /source/CimMessageAdapter.Tests
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /source/Infrastructure
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /source/IntegrationTests
    schedule:
      interval: monthly

  - package-ecosystem: nuget
    directory: /source/Tests
    schedule:
      interval: monthly
