# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.IntegrationTests"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.Application"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.Domain"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Common"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.EntryPoints.Processing"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.Infrastructure"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/source/business-workflow/source/Energinet.DataHub.MarketRoles.Tests"
    schedule:
      interval: "weekly"