# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.CimMessageAdapter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.CimMessageAdapter.Receiver"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.CimMessageAdapter.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.Application"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.Domain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.EntryPoints.Common"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.EntryPoints.Ingestion"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.EntryPoints.InternalCommandDispatcher"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.EntryPoints.LocalMessageHub"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.EntryPoints.Outbox"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.EntryPoints.Processing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.Infrastructure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.IntegrationTests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.Messaging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
