# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.ArchitectureTests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.Infrastructure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  
  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.IntegrationTests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  
  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.CimMessageAdapter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.CimMessageAdapter.Receiver"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/B2B.Transactions.CimMessageAdapter.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Processing.Application"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.ApplyDBMigrationsApp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Processing.Domain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.EntryPoints.Common"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.EntryPoints.Processing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Processing.Infrastructure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Processing.IntegrationTests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Energinet.DataHub.MarketRoles.Messaging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/Processing.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
