//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Energinet.DataHub.B2B.RSM.RSM034.V3.Notify {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    [System.Xml.Serialization.XmlRootAttribute("DK_NotifyChargeInformation", Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3", IsNullable=false)]
    public partial class DK_NotifyChargeInformationType {
        
        private EnergyDocument headerEnergyDocumentField;
        
        private EnergyContext processEnergyContextField;
        
        private ChargeEvent[] payloadChargeEventField;
        
        /// <remarks/>
        public EnergyDocument HeaderEnergyDocument {
            get {
                return this.headerEnergyDocumentField;
            }
            set {
                this.headerEnergyDocumentField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContext ProcessEnergyContext {
            get {
                return this.processEnergyContextField;
            }
            set {
                this.processEnergyContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PayloadChargeEvent")]
        public ChargeEvent[] PayloadChargeEvent {
            get {
                return this.payloadChargeEventField;
            }
            set {
                this.payloadChargeEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class EnergyDocument {
        
        private string identificationField;
        
        private EnergyDocumentDocumentType documentTypeField;
        
        private System.DateTime creationField;
        
        private EnergyParty senderEnergyPartyField;
        
        private EnergyParty recipientEnergyPartyField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyDocumentDocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Creation {
            get {
                return this.creationField;
            }
            set {
                this.creationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty SenderEnergyParty {
            get {
                return this.senderEnergyPartyField;
            }
            set {
                this.senderEnergyPartyField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty RecipientEnergyParty {
            get {
                return this.recipientEnergyPartyField;
            }
            set {
                this.recipientEnergyPartyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class EnergyDocumentDocumentType : DocumentNameCodeType_000098 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class DocumentNameCodeType_000098 {
        
        private DocumentNameCodeType_000098ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum DocumentNameCodeType_000098ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum DocumentNameCodeType_000098ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class TimeSeriesPeriod {
        
        private string resolutionDurationField;
        
        /// <remarks/>
        public string ResolutionDuration {
            get {
                return this.resolutionDurationField;
            }
            set {
                this.resolutionDurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class EnergyObservation {
        
        private string positionField;
        
        private decimal energyPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public decimal EnergyPrice {
            get {
                return this.energyPriceField;
            }
            set {
                this.energyPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class VATClassCodeType_DK0004 {
        
        private VATClassCodeType_DK0004ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private VATClassCodeType_DK0004ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VATClassCodeType_DK0004ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VATClassCodeType_DK0004ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum VATClassCodeType_DK0004ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum VATClassCodeType_DK0004ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class ChargeTypeCodeType_000134 {
        
        private ChargeTypeCodeType_000134ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private ChargeTypeCodeType_000134ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ChargeTypeCodeType_000134ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ChargeTypeCodeType_000134ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum ChargeTypeCodeType_000134ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum ChargeTypeCodeType_000134ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class ChargeInformation {
        
        private ChargeInformationChargeType chargeTypeField;
        
        private string partyChargeTypeIDField;
        
        private string descriptionField;
        
        private string longDescriptionField;
        
        private ChargeInformationVATClass vATClassField;
        
        private bool transparentInvoicingField;
        
        private bool taxIndicatorField;
        
        private EnergyObservation[] intervalEnergyObservationField;
        
        private TimeSeriesPeriod observationTimeSeriesPeriodField;
        
        private EnergyParty chargeTypeOwnerEnergyPartyField;
        
        /// <remarks/>
        public ChargeInformationChargeType ChargeType {
            get {
                return this.chargeTypeField;
            }
            set {
                this.chargeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PartyChargeTypeID {
            get {
                return this.partyChargeTypeIDField;
            }
            set {
                this.partyChargeTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LongDescription {
            get {
                return this.longDescriptionField;
            }
            set {
                this.longDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public ChargeInformationVATClass VATClass {
            get {
                return this.vATClassField;
            }
            set {
                this.vATClassField = value;
            }
        }
        
        /// <remarks/>
        public bool TransparentInvoicing {
            get {
                return this.transparentInvoicingField;
            }
            set {
                this.transparentInvoicingField = value;
            }
        }
        
        /// <remarks/>
        public bool TaxIndicator {
            get {
                return this.taxIndicatorField;
            }
            set {
                this.taxIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IntervalEnergyObservation")]
        public EnergyObservation[] IntervalEnergyObservation {
            get {
                return this.intervalEnergyObservationField;
            }
            set {
                this.intervalEnergyObservationField = value;
            }
        }
        
        /// <remarks/>
        public TimeSeriesPeriod ObservationTimeSeriesPeriod {
            get {
                return this.observationTimeSeriesPeriodField;
            }
            set {
                this.observationTimeSeriesPeriodField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty ChargeTypeOwnerEnergyParty {
            get {
                return this.chargeTypeOwnerEnergyPartyField;
            }
            set {
                this.chargeTypeOwnerEnergyPartyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class ChargeInformationChargeType : ChargeTypeCodeType_000134 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class ChargeInformationVATClass : VATClassCodeType_DK0004 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class EnergyParty {
        
        private PartyIdentifierType_000112 identificationField;
        
        /// <remarks/>
        public PartyIdentifierType_000112 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class PartyIdentifierType_000112 {
        
        private PartyIdentifierType_000112SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum PartyIdentifierType_000112SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum PartyIdentifierType_000112SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class DocumentFunctionCodeType_000118 {
        
        private DocumentFunctionCodeType_000118ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DocumentFunctionCodeType_000118ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentFunctionCodeType_000118ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentFunctionCodeType_000118ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum DocumentFunctionCodeType_000118ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum DocumentFunctionCodeType_000118ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class ChargeEvent {
        
        private string identificationField;
        
        private System.DateTime occurrenceField;
        
        private ChargeEventFunction functionField;
        
        private ChargeInformation relatedChargeChargeInformationField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Occurrence {
            get {
                return this.occurrenceField;
            }
            set {
                this.occurrenceField = value;
            }
        }
        
        /// <remarks/>
        public ChargeEventFunction Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        public ChargeInformation RelatedChargeChargeInformation {
            get {
                return this.relatedChargeChargeInformationField;
            }
            set {
                this.relatedChargeChargeInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class ChargeEventFunction : DocumentFunctionCodeType_000118 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class SectorAreaIdentificationCodeType_000116 {
        
        private SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum SectorAreaIdentificationCodeType_000116ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class BusinessRoleCodeType_000113 {
        
        private BusinessRoleCodeType_000113ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum BusinessRoleCodeType_000113ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum BusinessRoleCodeType_000113ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class BusinessReasonCodeType_000115 {
        
        private BusinessReasonCodeType_000115ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum BusinessReasonCodeType_000115ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public enum BusinessReasonCodeType_000115ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class EnergyContext {
        
        private EnergyContextEnergyBusinessProcess energyBusinessProcessField;
        
        private EnergyContextEnergyBusinessProcessRole energyBusinessProcessRoleField;
        
        private EnergyContextEnergyIndustryClassification energyIndustryClassificationField;
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcess EnergyBusinessProcess {
            get {
                return this.energyBusinessProcessField;
            }
            set {
                this.energyBusinessProcessField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcessRole EnergyBusinessProcessRole {
            get {
                return this.energyBusinessProcessRoleField;
            }
            set {
                this.energyBusinessProcessRoleField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyIndustryClassification EnergyIndustryClassification {
            get {
                return this.energyIndustryClassificationField;
            }
            set {
                this.energyIndustryClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class EnergyContextEnergyBusinessProcess : BusinessReasonCodeType_000115 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class EnergyContextEnergyBusinessProcessRole : BusinessRoleCodeType_000113 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NotifyChargeInformation:v3")]
    public partial class EnergyContextEnergyIndustryClassification : SectorAreaIdentificationCodeType_000116 {
    }
}
