// Copyright 2020 Energinet DataHub A/S
//
// Licensed under the Apache License, Version 2.0 (the "License2");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace SoapTest.RSM.RSM011.V3.Notify {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    [System.Xml.Serialization.XmlRootAttribute("DK_NonContinuousMetering", Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3", IsNullable=false)]
    public partial class DK_NonContinuousMeteringType {
        
        private EnergyDocument headerEnergyDocumentField;
        
        private EnergyContext processEnergyContextField;
        
        private NonContinuousEnergyTimeSeries[] payloadNonContinuousEnergyTimeSeriesField;
        
        /// <remarks/>
        public EnergyDocument HeaderEnergyDocument {
            get {
                return this.headerEnergyDocumentField;
            }
            set {
                this.headerEnergyDocumentField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContext ProcessEnergyContext {
            get {
                return this.processEnergyContextField;
            }
            set {
                this.processEnergyContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PayloadNonContinuousEnergyTimeSeries")]
        public NonContinuousEnergyTimeSeries[] PayloadNonContinuousEnergyTimeSeries {
            get {
                return this.payloadNonContinuousEnergyTimeSeriesField;
            }
            set {
                this.payloadNonContinuousEnergyTimeSeriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class EnergyDocument {
        
        private string identificationField;
        
        private EnergyDocumentDocumentType documentTypeField;
        
        private System.DateTime creationField;
        
        private EnergyParty senderEnergyPartyField;
        
        private EnergyParty recipientEnergyPartyField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyDocumentDocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Creation {
            get {
                return this.creationField;
            }
            set {
                this.creationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty SenderEnergyParty {
            get {
                return this.senderEnergyPartyField;
            }
            set {
                this.senderEnergyPartyField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty RecipientEnergyParty {
            get {
                return this.recipientEnergyPartyField;
            }
            set {
                this.recipientEnergyPartyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class EnergyDocumentDocumentType : DocumentNameCodeType_000098 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class DocumentNameCodeType_000098 {
        
        private DocumentNameCodeType_000098ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum DocumentNameCodeType_000098ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum DocumentNameCodeType_000098ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class MeasurementUnitCommonCodeType_000121 {
        
        private MeasurementUnitCommonCodeType_000121ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MeasurementUnitCommonCodeType_000121ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeasurementUnitCommonCodeType_000121ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeasurementUnitCommonCodeType_000121ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum MeasurementUnitCommonCodeType_000121ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum MeasurementUnitCommonCodeType_000121ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class EnergyProductIdentificationCodeType_000120 {
        
        private EnergyProductIdentificationCodeType_000120ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private EnergyProductIdentificationCodeType_000120ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EnergyProductIdentificationCodeType_000120ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EnergyProductIdentificationCodeType_000120ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum EnergyProductIdentificationCodeType_000120ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum EnergyProductIdentificationCodeType_000120ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class ProductCharacteristic {
        
        private ProductCharacteristicIdentification identificationField;
        
        private ProductCharacteristicUnitType unitTypeField;
        
        /// <remarks/>
        public ProductCharacteristicIdentification Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public ProductCharacteristicUnitType UnitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class ProductCharacteristicIdentification : EnergyProductIdentificationCodeType_000120 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class ProductCharacteristicUnitType : MeasurementUnitCommonCodeType_000121 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class QuantityQualityCodeType_000125 {
        
        private QuantityQualityCodeType_000125ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private QuantityQualityCodeType_000125ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QuantityQualityCodeType_000125ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QuantityQualityCodeType_000125ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum QuantityQualityCodeType_000125ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum QuantityQualityCodeType_000125ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class NonContinuousEnergyObservation {
        
        private decimal energyQuantityField;
        
        private bool energyQuantityFieldSpecified;
        
        private NonContinuousEnergyObservationQuantityQuality quantityQualityField;
        
        private decimal meterReadingField;
        
        private bool meterReadingFieldSpecified;
        
        private string positionField;
        
        /// <remarks/>
        public decimal EnergyQuantity {
            get {
                return this.energyQuantityField;
            }
            set {
                this.energyQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnergyQuantitySpecified {
            get {
                return this.energyQuantityFieldSpecified;
            }
            set {
                this.energyQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public NonContinuousEnergyObservationQuantityQuality QuantityQuality {
            get {
                return this.quantityQualityField;
            }
            set {
                this.quantityQualityField = value;
            }
        }
        
        /// <remarks/>
        public decimal MeterReading {
            get {
                return this.meterReadingField;
            }
            set {
                this.meterReadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeterReadingSpecified {
            get {
                return this.meterReadingFieldSpecified;
            }
            set {
                this.meterReadingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class NonContinuousEnergyObservationQuantityQuality : QuantityQualityCodeType_000125 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class ProfiledPeriod {
        
        private System.DateTime startField;
        
        private bool startFieldSpecified;
        
        private System.DateTime endField;
        
        private bool endFieldSpecified;
        
        /// <remarks/>
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndSpecified {
            get {
                return this.endFieldSpecified;
            }
            set {
                this.endFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class MeterFacility {
        
        private string meterIdentificationField;
        
        /// <remarks/>
        public string MeterIdentification {
            get {
                return this.meterIdentificationField;
            }
            set {
                this.meterIdentificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class DomainIdentifierType_000122 {
        
        private DomainIdentifierType_000122SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private DomainIdentifierType_000122SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DomainIdentifierType_000122SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DomainIdentifierType_000122SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum DomainIdentifierType_000122SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum DomainIdentifierType_000122SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class DomainLocation {
        
        private DomainIdentifierType_000122 identificationField;
        
        /// <remarks/>
        public DomainIdentifierType_000122 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class SettlementMethodCodeType_000145 {
        
        private SettlementMethodCodeType_000145ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private SettlementMethodCodeType_000145ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SettlementMethodCodeType_000145ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SettlementMethodCodeType_000145ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum SettlementMethodCodeType_000145ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum SettlementMethodCodeType_000145ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class MeteringPointTypeCodeType_000138 {
        
        private MeteringPointTypeCodeType_000138ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MeteringPointTypeCodeType_000138ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeteringPointTypeCodeType_000138ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeteringPointTypeCodeType_000138ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum MeteringPointTypeCodeType_000138ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum MeteringPointTypeCodeType_000138ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class MeasurementMeteringPointCharacteristic {
        
        private MeasurementMeteringPointCharacteristicTypeOfMeteringPoint typeOfMeteringPointField;
        
        private MeasurementMeteringPointCharacteristicSettlementMethod settlementMethodField;
        
        /// <remarks/>
        public MeasurementMeteringPointCharacteristicTypeOfMeteringPoint TypeOfMeteringPoint {
            get {
                return this.typeOfMeteringPointField;
            }
            set {
                this.typeOfMeteringPointField = value;
            }
        }
        
        /// <remarks/>
        public MeasurementMeteringPointCharacteristicSettlementMethod SettlementMethod {
            get {
                return this.settlementMethodField;
            }
            set {
                this.settlementMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class MeasurementMeteringPointCharacteristicTypeOfMeteringPoint : MeteringPointTypeCodeType_000138 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class MeasurementMeteringPointCharacteristicSettlementMethod : SettlementMethodCodeType_000145 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class DocumentFunctionCodeType_000118 {
        
        private DocumentFunctionCodeType_000118ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DocumentFunctionCodeType_000118ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentFunctionCodeType_000118ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentFunctionCodeType_000118ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum DocumentFunctionCodeType_000118ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum DocumentFunctionCodeType_000118ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class NonContinuousEnergyTimeSeries {
        
        private string identificationField;
        
        private NonContinuousEnergyTimeSeriesFunction functionField;
        
        private MeasurementMeteringPointCharacteristic detailMeasurementMeteringPointCharacteristicField;
        
        private DomainLocation meteringPointDomainLocationField;
        
        private MeterFacility meteringInstallationMeterFacilityField;
        
        private ProfiledPeriod durationProfiledPeriodField;
        
        private NonContinuousEnergyObservation intervalNonContinuousEnergyObservationField;
        
        private ProductCharacteristic includedProductCharacteristicField;
        
        private string originalBusinessDocumentField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public NonContinuousEnergyTimeSeriesFunction Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        public MeasurementMeteringPointCharacteristic DetailMeasurementMeteringPointCharacteristic {
            get {
                return this.detailMeasurementMeteringPointCharacteristicField;
            }
            set {
                this.detailMeasurementMeteringPointCharacteristicField = value;
            }
        }
        
        /// <remarks/>
        public DomainLocation MeteringPointDomainLocation {
            get {
                return this.meteringPointDomainLocationField;
            }
            set {
                this.meteringPointDomainLocationField = value;
            }
        }
        
        /// <remarks/>
        public MeterFacility MeteringInstallationMeterFacility {
            get {
                return this.meteringInstallationMeterFacilityField;
            }
            set {
                this.meteringInstallationMeterFacilityField = value;
            }
        }
        
        /// <remarks/>
        public ProfiledPeriod DurationProfiledPeriod {
            get {
                return this.durationProfiledPeriodField;
            }
            set {
                this.durationProfiledPeriodField = value;
            }
        }
        
        /// <remarks/>
        public NonContinuousEnergyObservation IntervalNonContinuousEnergyObservation {
            get {
                return this.intervalNonContinuousEnergyObservationField;
            }
            set {
                this.intervalNonContinuousEnergyObservationField = value;
            }
        }
        
        /// <remarks/>
        public ProductCharacteristic IncludedProductCharacteristic {
            get {
                return this.includedProductCharacteristicField;
            }
            set {
                this.includedProductCharacteristicField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalBusinessDocument {
            get {
                return this.originalBusinessDocumentField;
            }
            set {
                this.originalBusinessDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class NonContinuousEnergyTimeSeriesFunction : DocumentFunctionCodeType_000118 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class SectorAreaIdentificationCodeType_000116 {
        
        private SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum SectorAreaIdentificationCodeType_000116ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class BusinessRoleCodeType_000113 {
        
        private BusinessRoleCodeType_000113ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum BusinessRoleCodeType_000113ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum BusinessRoleCodeType_000113ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class BusinessReasonCodeType_000115 {
        
        private BusinessReasonCodeType_000115ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum BusinessReasonCodeType_000115ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum BusinessReasonCodeType_000115ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class EnergyContext {
        
        private EnergyContextEnergyBusinessProcess energyBusinessProcessField;
        
        private EnergyContextEnergyBusinessProcessRole energyBusinessProcessRoleField;
        
        private EnergyContextEnergyIndustryClassification energyIndustryClassificationField;
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcess EnergyBusinessProcess {
            get {
                return this.energyBusinessProcessField;
            }
            set {
                this.energyBusinessProcessField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcessRole EnergyBusinessProcessRole {
            get {
                return this.energyBusinessProcessRoleField;
            }
            set {
                this.energyBusinessProcessRoleField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyIndustryClassification EnergyIndustryClassification {
            get {
                return this.energyIndustryClassificationField;
            }
            set {
                this.energyIndustryClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class EnergyContextEnergyBusinessProcess : BusinessReasonCodeType_000115 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class EnergyContextEnergyBusinessProcessRole : BusinessRoleCodeType_000113 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class EnergyContextEnergyIndustryClassification : SectorAreaIdentificationCodeType_000116 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class PartyIdentifierType_000112 {
        
        private PartyIdentifierType_000112SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum PartyIdentifierType_000112SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public enum PartyIdentifierType_000112SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_NonContinuousMetering:v3")]
    public partial class EnergyParty {
        
        private PartyIdentifierType_000112 identificationField;
        
        /// <remarks/>
        public PartyIdentifierType_000112 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
}
