//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace SoapTest.RSM.RSM002.V3.Confirm {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    [System.Xml.Serialization.XmlRootAttribute("DK_ConfirmCancelChangeOfSupplier", Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3", IsNullable=false)]
    public partial class DK_ConfirmCancelChangeOfSupplierType {
        
        private EnergyDocument headerEnergyDocumentField;
        
        private EnergyContext processEnergyContextField;
        
        private ResponseEvent[] payloadResponseEventField;
        
        /// <remarks/>
        public EnergyDocument HeaderEnergyDocument {
            get {
                return this.headerEnergyDocumentField;
            }
            set {
                this.headerEnergyDocumentField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContext ProcessEnergyContext {
            get {
                return this.processEnergyContextField;
            }
            set {
                this.processEnergyContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PayloadResponseEvent")]
        public ResponseEvent[] PayloadResponseEvent {
            get {
                return this.payloadResponseEventField;
            }
            set {
                this.payloadResponseEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class EnergyDocument {
        
        private string identificationField;
        
        private EnergyDocumentDocumentType documentTypeField;
        
        private System.DateTime creationField;
        
        private EnergyParty senderEnergyPartyField;
        
        private EnergyParty recipientEnergyPartyField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyDocumentDocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Creation {
            get {
                return this.creationField;
            }
            set {
                this.creationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty SenderEnergyParty {
            get {
                return this.senderEnergyPartyField;
            }
            set {
                this.senderEnergyPartyField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty RecipientEnergyParty {
            get {
                return this.recipientEnergyPartyField;
            }
            set {
                this.recipientEnergyPartyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class EnergyDocumentDocumentType : DocumentNameCodeType_000098 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class DocumentNameCodeType_000098 {
        
        private DocumentNameCodeType_000098ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum DocumentNameCodeType_000098ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum DocumentNameCodeType_000098ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class DomainIdentifierType_000122 {
        
        private DomainIdentifierType_000122SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private DomainIdentifierType_000122SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DomainIdentifierType_000122SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DomainIdentifierType_000122SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum DomainIdentifierType_000122SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum DomainIdentifierType_000122SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class DomainLocation {
        
        private DomainIdentifierType_000122 identificationField;
        
        /// <remarks/>
        public DomainIdentifierType_000122 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class ResponseConditionCodeType_000130 {
        
        private ResponseConditionCodeType_000130ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private ResponseConditionCodeType_000130ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ResponseConditionCodeType_000130ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ResponseConditionCodeType_000130ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum ResponseConditionCodeType_000130ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum ResponseConditionCodeType_000130ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class ResponseEvent {
        
        private string identificationField;
        
        private ResponseEventStatusType statusTypeField;
        
        private DomainLocation meteringPointDomainLocationField;
        
        private string originalBusinessDocumentField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public ResponseEventStatusType StatusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
            }
        }
        
        /// <remarks/>
        public DomainLocation MeteringPointDomainLocation {
            get {
                return this.meteringPointDomainLocationField;
            }
            set {
                this.meteringPointDomainLocationField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalBusinessDocument {
            get {
                return this.originalBusinessDocumentField;
            }
            set {
                this.originalBusinessDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class ResponseEventStatusType : ResponseConditionCodeType_000130 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class SectorAreaIdentificationCodeType_000116 {
        
        private SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum SectorAreaIdentificationCodeType_000116ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class BusinessRoleCodeType_000113 {
        
        private BusinessRoleCodeType_000113ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum BusinessRoleCodeType_000113ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum BusinessRoleCodeType_000113ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class BusinessReasonCodeType_000115 {
        
        private BusinessReasonCodeType_000115ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum BusinessReasonCodeType_000115ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum BusinessReasonCodeType_000115ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class EnergyContext {
        
        private EnergyContextEnergyBusinessProcess energyBusinessProcessField;
        
        private EnergyContextEnergyBusinessProcessRole energyBusinessProcessRoleField;
        
        private EnergyContextEnergyIndustryClassification energyIndustryClassificationField;
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcess EnergyBusinessProcess {
            get {
                return this.energyBusinessProcessField;
            }
            set {
                this.energyBusinessProcessField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcessRole EnergyBusinessProcessRole {
            get {
                return this.energyBusinessProcessRoleField;
            }
            set {
                this.energyBusinessProcessRoleField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyIndustryClassification EnergyIndustryClassification {
            get {
                return this.energyIndustryClassificationField;
            }
            set {
                this.energyIndustryClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class EnergyContextEnergyBusinessProcess : BusinessReasonCodeType_000115 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class EnergyContextEnergyBusinessProcessRole : BusinessRoleCodeType_000113 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class EnergyContextEnergyIndustryClassification : SectorAreaIdentificationCodeType_000116 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class PartyIdentifierType_000112 {
        
        private PartyIdentifierType_000112SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum PartyIdentifierType_000112SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public enum PartyIdentifierType_000112SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ConfirmCancelChangeOfSupplier:v3")]
    public partial class EnergyParty {
        
        private PartyIdentifierType_000112 identificationField;
        
        /// <remarks/>
        public PartyIdentifierType_000112 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
}
