//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright 2020 Energinet DataHub A/S
//
// Licensed under the Apache License, Version 2.0 (the "License2");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace Energinet.DataHub.EDI.SubsystemTests.Drivers.Ebix {


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:www:datahub:dk:b2b:service:v01", ConfigurationName="DataHubService.marketMessagingB2BServiceV01PortType")]
    public interface marketMessagingB2BServiceV01PortType {

        // CODEGEN: Generating message contract since the wrapper namespace (urn:www:datahub:dk:b2b:v01) of message sendMessageRequest does not match the default value (urn:www:datahub:dk:b2b:service:v01)
        [System.ServiceModel.OperationContractAttribute(Action="sendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sendMessageResponse sendMessage(sendMessageRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="sendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<sendMessageResponse> sendMessageAsync(sendMessageRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (urn:www:datahub:dk:b2b:v01) of message getMessageRequest does not match the default value (urn:www:datahub:dk:b2b:service:v01)
        [System.ServiceModel.OperationContractAttribute(Action="getMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        getMessageResponse getMessage(getMessageRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="getMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<getMessageResponse> getMessageAsync(getMessageRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (urn:www:datahub:dk:b2b:v01) of message getMessageIdsRequest does not match the default value (urn:www:datahub:dk:b2b:service:v01)
        [System.ServiceModel.OperationContractAttribute(Action="getMessageIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        getMessageIdsResponse getMessageIds(getMessageIdsRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="getMessageIds", ReplyAction="*")]
        System.Threading.Tasks.Task<getMessageIdsResponse> getMessageIdsAsync(getMessageIdsRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="queryData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        queryDataResponse queryData(queryDataRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="queryData", ReplyAction="*")]
        System.Threading.Tasks.Task<queryDataResponse> queryDataAsync(queryDataRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (urn:www:datahub:dk:b2b:v01) of message peekMessageRequest does not match the default value (urn:www:datahub:dk:b2b:service:v01)
        [System.ServiceModel.OperationContractAttribute(Action="peekMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        peekMessageResponse peekMessage(peekMessageRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="peekMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<peekMessageResponse> peekMessageAsync(peekMessageRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (urn:www:datahub:dk:b2b:v01) of message dequeueMessageRequest does not match the default value (urn:www:datahub:dk:b2b:service:v01)
        [System.ServiceModel.OperationContractAttribute(Action="dequeueMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        dequeueMessageResponse dequeueMessage(dequeueMessageRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="dequeueMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<dequeueMessageResponse> dequeueMessageAsync(dequeueMessageRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www:datahub:dk:b2b:v01")]
    public partial class MessageContainer_Type : object, System.ComponentModel.INotifyPropertyChanged {

        private string messageReferenceField;

        private string documentTypeField;

        private MessageType_Type messageTypeField;

        private System.Xml.XmlElement payloadField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageReference {
            get {
                return this.messageReferenceField;
            }
            set {
                this.messageReferenceField = value;
                this.RaisePropertyChanged("MessageReference");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MessageType_Type MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Xml.XmlElement Payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [Serializable()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:www:datahub:dk:b2b:v01")]
    public enum MessageType_Type {

        /// <remarks/>
        XML,

        /// <remarks/>
        EDIFACT,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageRequest", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class sendMessageRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=0)]
        public MessageContainer_Type MessageContainer;

        public sendMessageRequest() {
        }

        public sendMessageRequest(MessageContainer_Type MessageContainer) {
            this.MessageContainer = MessageContainer;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class sendMessageResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=0)]
        public string MessageId;

        public sendMessageResponse() {
        }

        public sendMessageResponse(string MessageId) {
            this.MessageId = MessageId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageRequest", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class getMessageRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=0)]
        public string MessageId;

        public getMessageRequest() {
        }

        public getMessageRequest(string MessageId) {
            this.MessageId = MessageId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageResponse", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class getMessageResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=0)]
        public MessageContainer_Type MessageContainer;

        public getMessageResponse() {
        }

        public getMessageResponse(MessageContainer_Type MessageContainer) {
            this.MessageContainer = MessageContainer;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageIdsRequest", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class getMessageIdsRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=0)]
        public System.DateTime From;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=1)]
        public System.DateTime To;

        public getMessageIdsRequest() {
        }

        public getMessageIdsRequest(System.DateTime From, System.DateTime To) {
            this.From = From;
            this.To = To;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageIdsResponse", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class getMessageIdsResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MessageId", IsNullable=false)]
        public string[] MessageIdList;

        public getMessageIdsResponse() {
        }

        public getMessageIdsResponse(string[] MessageIdList) {
            this.MessageIdList = MessageIdList;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryDataRequest", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class queryDataRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;

        public queryDataRequest() {
        }

        public queryDataRequest(System.Xml.XmlElement[] Any) {
            this.Any = Any;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryDataResponse", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class queryDataResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;

        public queryDataResponse() {
        }

        public queryDataResponse(System.Xml.XmlElement[] Any) {
            this.Any = Any;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PeekMessageRequest", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class peekMessageRequest {

        public peekMessageRequest() {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PeekMessageResponse", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class peekMessageResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=0)]
        public MessageContainer_Type MessageContainer;

        public peekMessageResponse() {
        }

        public peekMessageResponse(MessageContainer_Type MessageContainer) {
            this.MessageContainer = MessageContainer;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DequeueMessageRequest", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class dequeueMessageRequest {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:www:datahub:dk:b2b:v01", Order=0)]
        public string MessageId;

        public dequeueMessageRequest() {
        }

        public dequeueMessageRequest(string MessageId) {
            this.MessageId = MessageId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DequeueMessageResponse", WrapperNamespace="urn:www:datahub:dk:b2b:v01", IsWrapped=true)]
    public partial class dequeueMessageResponse {

        public dequeueMessageResponse() {
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface marketMessagingB2BServiceV01PortTypeChannel : marketMessagingB2BServiceV01PortType, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class marketMessagingB2BServiceV01PortTypeClient : System.ServiceModel.ClientBase<marketMessagingB2BServiceV01PortType>, marketMessagingB2BServiceV01PortType {

        public marketMessagingB2BServiceV01PortTypeClient() {
        }

        public marketMessagingB2BServiceV01PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress) {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sendMessageResponse marketMessagingB2BServiceV01PortType.sendMessage(sendMessageRequest request) {
            return base.Channel.sendMessage(request);
        }

        public string sendMessage(MessageContainer_Type MessageContainer) {
            sendMessageRequest inValue = new sendMessageRequest();
            inValue.MessageContainer = MessageContainer;
            sendMessageResponse retVal = ((marketMessagingB2BServiceV01PortType)(this)).sendMessage(inValue);
            return retVal.MessageId;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sendMessageResponse> marketMessagingB2BServiceV01PortType.sendMessageAsync(sendMessageRequest request) {
            return base.Channel.sendMessageAsync(request);
        }

        public System.Threading.Tasks.Task<sendMessageResponse> sendMessageAsync(MessageContainer_Type MessageContainer) {
            sendMessageRequest inValue = new sendMessageRequest();
            inValue.MessageContainer = MessageContainer;
            return ((marketMessagingB2BServiceV01PortType)(this)).sendMessageAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getMessageResponse marketMessagingB2BServiceV01PortType.getMessage(getMessageRequest request) {
            return base.Channel.getMessage(request);
        }

        public MessageContainer_Type getMessage(string MessageId) {
            getMessageRequest inValue = new getMessageRequest();
            inValue.MessageId = MessageId;
            getMessageResponse retVal = ((marketMessagingB2BServiceV01PortType)(this)).getMessage(inValue);
            return retVal.MessageContainer;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getMessageResponse> marketMessagingB2BServiceV01PortType.getMessageAsync(getMessageRequest request) {
            return base.Channel.getMessageAsync(request);
        }

        public System.Threading.Tasks.Task<getMessageResponse> getMessageAsync(string MessageId) {
            getMessageRequest inValue = new getMessageRequest();
            inValue.MessageId = MessageId;
            return ((marketMessagingB2BServiceV01PortType)(this)).getMessageAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getMessageIdsResponse marketMessagingB2BServiceV01PortType.getMessageIds(getMessageIdsRequest request) {
            return base.Channel.getMessageIds(request);
        }

        public string[] getMessageIds(System.DateTime From, System.DateTime To) {
            getMessageIdsRequest inValue = new getMessageIdsRequest();
            inValue.From = From;
            inValue.To = To;
            getMessageIdsResponse retVal = ((marketMessagingB2BServiceV01PortType)(this)).getMessageIds(inValue);
            return retVal.MessageIdList;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getMessageIdsResponse> marketMessagingB2BServiceV01PortType.getMessageIdsAsync(getMessageIdsRequest request) {
            return base.Channel.getMessageIdsAsync(request);
        }

        public System.Threading.Tasks.Task<getMessageIdsResponse> getMessageIdsAsync(System.DateTime From, System.DateTime To) {
            getMessageIdsRequest inValue = new getMessageIdsRequest();
            inValue.From = From;
            inValue.To = To;
            return ((marketMessagingB2BServiceV01PortType)(this)).getMessageIdsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        queryDataResponse marketMessagingB2BServiceV01PortType.queryData(queryDataRequest request) {
            return base.Channel.queryData(request);
        }

        public void queryData(ref System.Xml.XmlElement[] Any) {
            queryDataRequest inValue = new queryDataRequest();
            inValue.Any = Any;
            queryDataResponse retVal = ((marketMessagingB2BServiceV01PortType)(this)).queryData(inValue);
            Any = retVal.Any;
        }

        public System.Threading.Tasks.Task<queryDataResponse> queryDataAsync(queryDataRequest request) {
            return base.Channel.queryDataAsync(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        peekMessageResponse marketMessagingB2BServiceV01PortType.peekMessage(peekMessageRequest request) {
            return base.Channel.peekMessage(request);
        }

        public MessageContainer_Type peekMessage() {
            peekMessageRequest inValue = new peekMessageRequest();
            peekMessageResponse retVal = ((marketMessagingB2BServiceV01PortType)(this)).peekMessage(inValue);
            return retVal.MessageContainer;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<peekMessageResponse> marketMessagingB2BServiceV01PortType.peekMessageAsync(peekMessageRequest request) {
            return base.Channel.peekMessageAsync(request);
        }

        public System.Threading.Tasks.Task<peekMessageResponse> peekMessageAsync() {
            peekMessageRequest inValue = new peekMessageRequest();
            return ((marketMessagingB2BServiceV01PortType)(this)).peekMessageAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dequeueMessageResponse marketMessagingB2BServiceV01PortType.dequeueMessage(dequeueMessageRequest request) {
            return base.Channel.dequeueMessage(request);
        }

        public void dequeueMessage(string MessageId) {
            dequeueMessageRequest inValue = new dequeueMessageRequest();
            inValue.MessageId = MessageId;
            dequeueMessageResponse retVal = ((marketMessagingB2BServiceV01PortType)(this)).dequeueMessage(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dequeueMessageResponse> marketMessagingB2BServiceV01PortType.dequeueMessageAsync(dequeueMessageRequest request) {
            return base.Channel.dequeueMessageAsync(request);
        }

        public System.Threading.Tasks.Task<dequeueMessageResponse> dequeueMessageAsync(string MessageId) {
            dequeueMessageRequest inValue = new dequeueMessageRequest();
            inValue.MessageId = MessageId;
            return ((marketMessagingB2BServiceV01PortType)(this)).dequeueMessageAsync(inValue);
        }
    }
}
