// Copyright 2020 Energinet DataHub A/S
//
// Licensed under the Apache License, Version 2.0 (the "License2");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace SoapTest.RSM.RSM029.V3.Response {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    [System.Xml.Serialization.XmlRootAttribute("DK_ResponseMasterDataConsumer", Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3", IsNullable=false)]
    public partial class DK_ResponseMasterDataConsumerType {
        
        private EnergyDocument headerEnergyDocumentField;
        
        private EnergyContext processEnergyContextField;
        
        private MasterDataMeteringPointPartyEvent[] payloadMasterDataMeteringPointPartyEventField;
        
        /// <remarks/>
        public EnergyDocument HeaderEnergyDocument {
            get {
                return this.headerEnergyDocumentField;
            }
            set {
                this.headerEnergyDocumentField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContext ProcessEnergyContext {
            get {
                return this.processEnergyContextField;
            }
            set {
                this.processEnergyContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PayloadMasterDataMeteringPointPartyEvent")]
        public MasterDataMeteringPointPartyEvent[] PayloadMasterDataMeteringPointPartyEvent {
            get {
                return this.payloadMasterDataMeteringPointPartyEventField;
            }
            set {
                this.payloadMasterDataMeteringPointPartyEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class EnergyDocument {
        
        private string identificationField;
        
        private EnergyDocumentDocumentType documentTypeField;
        
        private System.DateTime creationField;
        
        private EnergyParty senderEnergyPartyField;
        
        private EnergyParty recipientEnergyPartyField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyDocumentDocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Creation {
            get {
                return this.creationField;
            }
            set {
                this.creationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty SenderEnergyParty {
            get {
                return this.senderEnergyPartyField;
            }
            set {
                this.senderEnergyPartyField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty RecipientEnergyParty {
            get {
                return this.recipientEnergyPartyField;
            }
            set {
                this.recipientEnergyPartyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class EnergyDocumentDocumentType : DocumentNameCodeType_000098 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class DocumentNameCodeType_000098 {
        
        private DocumentNameCodeType_000098ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum DocumentNameCodeType_000098ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum DocumentNameCodeType_000098ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class DomainIdentifierType_000122 {
        
        private DomainIdentifierType_000122SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private DomainIdentifierType_000122SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DomainIdentifierType_000122SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DomainIdentifierType_000122SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum DomainIdentifierType_000122SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum DomainIdentifierType_000122SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class DomainLocation {
        
        private DomainIdentifierType_000122 identificationField;
        
        /// <remarks/>
        public DomainIdentifierType_000122 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class ConsumerParty {
        
        private string nameField;
        
        private string cVRField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string CVR {
            get {
                return this.cVRField;
            }
            set {
                this.cVRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class LocationAddress {
        
        private string streetNameField;
        
        private string streetCodeField;
        
        private string buildingNumberField;
        
        private string floorIdentificationField;
        
        private string roomIdentificationField;
        
        private string postOfficeBoxField;
        
        private string citySubDivisionNameField;
        
        private string postcodeField;
        
        private string cityNameField;
        
        private string municipalityCodeField;
        
        private string countryNameField;
        
        private string dARReferenceField;
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BuildingNumber {
            get {
                return this.buildingNumberField;
            }
            set {
                this.buildingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FloorIdentification {
            get {
                return this.floorIdentificationField;
            }
            set {
                this.floorIdentificationField = value;
            }
        }
        
        /// <remarks/>
        public string RoomIdentification {
            get {
                return this.roomIdentificationField;
            }
            set {
                this.roomIdentificationField = value;
            }
        }
        
        /// <remarks/>
        public string PostOfficeBox {
            get {
                return this.postOfficeBoxField;
            }
            set {
                this.postOfficeBoxField = value;
            }
        }
        
        /// <remarks/>
        public string CitySubDivisionName {
            get {
                return this.citySubDivisionNameField;
            }
            set {
                this.citySubDivisionNameField = value;
            }
        }
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string MunicipalityCode {
            get {
                return this.municipalityCodeField;
            }
            set {
                this.municipalityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public string DARReference {
            get {
                return this.dARReferenceField;
            }
            set {
                this.dARReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class MPRelationTypeCodeType_DK2013071606 {
        
        private MPRelationTypeCodeType_DK2013071606ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MPRelationTypeCodeType_DK2013071606ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MPRelationTypeCodeType_DK2013071606ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MPRelationTypeCodeType_DK2013071606ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum MPRelationTypeCodeType_DK2013071606ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum MPRelationTypeCodeType_DK2013071606ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class MPAdministrativeParty {
        
        private string name1Field;
        
        private string attentionField;
        
        private MPAdministrativePartyMPRelationType mPRelationTypeField;
        
        private LocationAddress administrativePartyAddressLocationAddressField;
        
        private string phoneField;
        
        private string mobileField;
        
        private string emailField;
        
        private bool protectedAddressField;
        
        private bool protectedAddressFieldSpecified;
        
        /// <remarks/>
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        public string Attention {
            get {
                return this.attentionField;
            }
            set {
                this.attentionField = value;
            }
        }
        
        /// <remarks/>
        public MPAdministrativePartyMPRelationType MPRelationType {
            get {
                return this.mPRelationTypeField;
            }
            set {
                this.mPRelationTypeField = value;
            }
        }
        
        /// <remarks/>
        public LocationAddress AdministrativePartyAddressLocationAddress {
            get {
                return this.administrativePartyAddressLocationAddressField;
            }
            set {
                this.administrativePartyAddressLocationAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public bool ProtectedAddress {
            get {
                return this.protectedAddressField;
            }
            set {
                this.protectedAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProtectedAddressSpecified {
            get {
                return this.protectedAddressFieldSpecified;
            }
            set {
                this.protectedAddressFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class MPAdministrativePartyMPRelationType : MPRelationTypeCodeType_DK2013071606 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class MeteringPointPartyCharacteristic {
        
        private bool electricalHeatingField;
        
        private bool electricalHeatingFieldSpecified;
        
        private System.DateTime electricalHeatingDateField;
        
        private bool electricalHeatingDateFieldSpecified;
        
        private string webAccessCodeField;
        
        private string consumerCategoryField;
        
        private MPAdministrativeParty[] administrativePartyMPAdministrativePartyField;
        
        private ConsumerParty firstConsumerConsumerPartyField;
        
        private ConsumerParty secondConsumerConsumerPartyField;
        
        private bool hasBalanceSupplierField;
        
        private bool hasBalanceSupplierFieldSpecified;
        
        private System.DateTime supplyStartField;
        
        private bool supplyStartFieldSpecified;
        
        private bool protectedNameField;
        
        private bool protectedNameFieldSpecified;
        
        /// <remarks/>
        public bool ElectricalHeating {
            get {
                return this.electricalHeatingField;
            }
            set {
                this.electricalHeatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectricalHeatingSpecified {
            get {
                return this.electricalHeatingFieldSpecified;
            }
            set {
                this.electricalHeatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ElectricalHeatingDate {
            get {
                return this.electricalHeatingDateField;
            }
            set {
                this.electricalHeatingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectricalHeatingDateSpecified {
            get {
                return this.electricalHeatingDateFieldSpecified;
            }
            set {
                this.electricalHeatingDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string WebAccessCode {
            get {
                return this.webAccessCodeField;
            }
            set {
                this.webAccessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ConsumerCategory {
            get {
                return this.consumerCategoryField;
            }
            set {
                this.consumerCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdministrativePartyMPAdministrativeParty")]
        public MPAdministrativeParty[] AdministrativePartyMPAdministrativeParty {
            get {
                return this.administrativePartyMPAdministrativePartyField;
            }
            set {
                this.administrativePartyMPAdministrativePartyField = value;
            }
        }
        
        /// <remarks/>
        public ConsumerParty FirstConsumerConsumerParty {
            get {
                return this.firstConsumerConsumerPartyField;
            }
            set {
                this.firstConsumerConsumerPartyField = value;
            }
        }
        
        /// <remarks/>
        public ConsumerParty SecondConsumerConsumerParty {
            get {
                return this.secondConsumerConsumerPartyField;
            }
            set {
                this.secondConsumerConsumerPartyField = value;
            }
        }
        
        /// <remarks/>
        public bool HasBalanceSupplier {
            get {
                return this.hasBalanceSupplierField;
            }
            set {
                this.hasBalanceSupplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasBalanceSupplierSpecified {
            get {
                return this.hasBalanceSupplierFieldSpecified;
            }
            set {
                this.hasBalanceSupplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SupplyStart {
            get {
                return this.supplyStartField;
            }
            set {
                this.supplyStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupplyStartSpecified {
            get {
                return this.supplyStartFieldSpecified;
            }
            set {
                this.supplyStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ProtectedName {
            get {
                return this.protectedNameField;
            }
            set {
                this.protectedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProtectedNameSpecified {
            get {
                return this.protectedNameFieldSpecified;
            }
            set {
                this.protectedNameFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class MasterDataMeteringPointPartyEvent {
        
        private string identificationField;
        
        private System.DateTime occurrenceField;
        
        private MeteringPointPartyCharacteristic meteringPointPartyDetailMeteringPointPartyCharacteristicField;
        
        private string originalBusinessDocumentField;
        
        private DomainLocation meteringPointDomainLocationField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Occurrence {
            get {
                return this.occurrenceField;
            }
            set {
                this.occurrenceField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointPartyCharacteristic MeteringPointPartyDetailMeteringPointPartyCharacteristic {
            get {
                return this.meteringPointPartyDetailMeteringPointPartyCharacteristicField;
            }
            set {
                this.meteringPointPartyDetailMeteringPointPartyCharacteristicField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalBusinessDocument {
            get {
                return this.originalBusinessDocumentField;
            }
            set {
                this.originalBusinessDocumentField = value;
            }
        }
        
        /// <remarks/>
        public DomainLocation MeteringPointDomainLocation {
            get {
                return this.meteringPointDomainLocationField;
            }
            set {
                this.meteringPointDomainLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class SectorAreaIdentificationCodeType_000116 {
        
        private SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum SectorAreaIdentificationCodeType_000116ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class BusinessRoleCodeType_000113 {
        
        private BusinessRoleCodeType_000113ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum BusinessRoleCodeType_000113ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum BusinessRoleCodeType_000113ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class BusinessReasonCodeType_000115 {
        
        private BusinessReasonCodeType_000115ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum BusinessReasonCodeType_000115ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum BusinessReasonCodeType_000115ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class EnergyContext {
        
        private EnergyContextEnergyBusinessProcess energyBusinessProcessField;
        
        private EnergyContextEnergyBusinessProcessRole energyBusinessProcessRoleField;
        
        private EnergyContextEnergyIndustryClassification energyIndustryClassificationField;
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcess EnergyBusinessProcess {
            get {
                return this.energyBusinessProcessField;
            }
            set {
                this.energyBusinessProcessField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcessRole EnergyBusinessProcessRole {
            get {
                return this.energyBusinessProcessRoleField;
            }
            set {
                this.energyBusinessProcessRoleField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyIndustryClassification EnergyIndustryClassification {
            get {
                return this.energyIndustryClassificationField;
            }
            set {
                this.energyIndustryClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class EnergyContextEnergyBusinessProcess : BusinessReasonCodeType_000115 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class EnergyContextEnergyBusinessProcessRole : BusinessRoleCodeType_000113 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class EnergyContextEnergyIndustryClassification : SectorAreaIdentificationCodeType_000116 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class PartyIdentifierType_000112 {
        
        private PartyIdentifierType_000112SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum PartyIdentifierType_000112SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public enum PartyIdentifierType_000112SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_ResponseMasterDataConsumer:v3")]
    public partial class EnergyParty {
        
        private PartyIdentifierType_000112 identificationField;
        
        /// <remarks/>
        public PartyIdentifierType_000112 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
}
