//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Energinet.DataHub.EDI.Infrastructure.EbixMessageAdapter.RSM.RSM021.V3.Request {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    [System.Xml.Serialization.XmlRootAttribute("DK_RequestUpdateMasterDataMeteringPoint", Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3", IsNullable=false)]
    public partial class DK_RequestUpdateMasterDataMeteringPointType {
        
        private EnergyDocument headerEnergyDocumentField;
        
        private EnergyContext processEnergyContextField;
        
        private MasterDataMPEvent[] payloadMasterDataMPEventField;
        
        /// <remarks/>
        public EnergyDocument HeaderEnergyDocument {
            get {
                return this.headerEnergyDocumentField;
            }
            set {
                this.headerEnergyDocumentField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContext ProcessEnergyContext {
            get {
                return this.processEnergyContextField;
            }
            set {
                this.processEnergyContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PayloadMasterDataMPEvent")]
        public MasterDataMPEvent[] PayloadMasterDataMPEvent {
            get {
                return this.payloadMasterDataMPEventField;
            }
            set {
                this.payloadMasterDataMPEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class EnergyDocument {
        
        private string identificationField;
        
        private EnergyDocumentDocumentType documentTypeField;
        
        private System.DateTime creationField;
        
        private EnergyParty senderEnergyPartyField;
        
        private EnergyParty recipientEnergyPartyField;
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyDocumentDocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Creation {
            get {
                return this.creationField;
            }
            set {
                this.creationField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty SenderEnergyParty {
            get {
                return this.senderEnergyPartyField;
            }
            set {
                this.senderEnergyPartyField = value;
            }
        }
        
        /// <remarks/>
        public EnergyParty RecipientEnergyParty {
            get {
                return this.recipientEnergyPartyField;
            }
            set {
                this.recipientEnergyPartyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class EnergyDocumentDocumentType : DocumentNameCodeType_000098 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class DocumentNameCodeType_000098 {
        
        private DocumentNameCodeType_000098ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentNameCodeType_000098ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum DocumentNameCodeType_000098ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum DocumentNameCodeType_000098ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class DocumentFunctionCodeType_000118 {
        
        private DocumentFunctionCodeType_000118ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DocumentFunctionCodeType_000118ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentFunctionCodeType_000118ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentFunctionCodeType_000118ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum DocumentFunctionCodeType_000118ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum DocumentFunctionCodeType_000118ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeterReadingTypeCodeType_000137 {
        
        private MeterReadingTypeCodeType_000137ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MeterReadingTypeCodeType_000137ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeterReadingTypeCodeType_000137ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeterReadingTypeCodeType_000137ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MeterReadingTypeCodeType_000137ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MeterReadingTypeCodeType_000137ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeterCharacteristic {
        
        private string numberOfDigitsField;
        
        private decimal conversionFactorField;
        
        private bool conversionFactorFieldSpecified;
        
        private MeterCharacteristicUnitType unitTypeField;
        
        private MeterCharacteristicMeterReadingType meterReadingTypeField;
        
        /// <remarks/>
        public string NumberOfDigits {
            get {
                return this.numberOfDigitsField;
            }
            set {
                this.numberOfDigitsField = value;
            }
        }
        
        /// <remarks/>
        public decimal ConversionFactor {
            get {
                return this.conversionFactorField;
            }
            set {
                this.conversionFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConversionFactorSpecified {
            get {
                return this.conversionFactorFieldSpecified;
            }
            set {
                this.conversionFactorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MeterCharacteristicUnitType UnitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
            }
        }
        
        /// <remarks/>
        public MeterCharacteristicMeterReadingType MeterReadingType {
            get {
                return this.meterReadingTypeField;
            }
            set {
                this.meterReadingTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeterCharacteristicUnitType : MeasurementUnitCommonCodeType_000121 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeasurementUnitCommonCodeType_000121 {
        
        private MeasurementUnitCommonCodeType_000121ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MeasurementUnitCommonCodeType_000121ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeasurementUnitCommonCodeType_000121ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeasurementUnitCommonCodeType_000121ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MeasurementUnitCommonCodeType_000121ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MeasurementUnitCommonCodeType_000121ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeterCharacteristicMeterReadingType : MeterReadingTypeCodeType_000137 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class RelatedMeteringPoint {
        
        private DomainLocation identificationDomainLocationField;
        
        /// <remarks/>
        public DomainLocation IdentificationDomainLocation {
            get {
                return this.identificationDomainLocationField;
            }
            set {
                this.identificationDomainLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class DomainLocation {
        
        private DomainIdentifierType_000122 identificationField;
        
        /// <remarks/>
        public DomainIdentifierType_000122 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class DomainIdentifierType_000122 {
        
        private DomainIdentifierType_000122SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private DomainIdentifierType_000122SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DomainIdentifierType_000122SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DomainIdentifierType_000122SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum DomainIdentifierType_000122SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum DomainIdentifierType_000122SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeterFacility {
        
        private string meterIdentificationField;
        
        /// <remarks/>
        public string MeterIdentification {
            get {
                return this.meterIdentificationField;
            }
            set {
                this.meterIdentificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MPAddressWashIstructionTypeCodeCodeType_000156 {
        
        private MPAddressWashIstructionTypeCodeCodeType_000156ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MPAddressWashIstructionTypeCodeCodeType_000156ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MPAddressWashIstructionTypeCodeCodeType_000156ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MPAddressWashIstructionTypeCodeCodeType_000156ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MPAddressWashIstructionTypeCodeCodeType_000156ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MPAddressWashIstructionTypeCodeCodeType_000156ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class LocationAddress {
        
        private string streetNameField;
        
        private string streetCodeField;
        
        private string buildingNumberField;
        
        private string floorIdentificationField;
        
        private string roomIdentificationField;
        
        private string citySubDivisionNameField;
        
        private string postcodeField;
        
        private string cityNameField;
        
        private string municipalityCodeField;
        
        private string countryNameField;
        
        private LocationAddressMPAddressWashInstructions mPAddressWashInstructionsField;
        
        private string dARReferenceField;
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BuildingNumber {
            get {
                return this.buildingNumberField;
            }
            set {
                this.buildingNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FloorIdentification {
            get {
                return this.floorIdentificationField;
            }
            set {
                this.floorIdentificationField = value;
            }
        }
        
        /// <remarks/>
        public string RoomIdentification {
            get {
                return this.roomIdentificationField;
            }
            set {
                this.roomIdentificationField = value;
            }
        }
        
        /// <remarks/>
        public string CitySubDivisionName {
            get {
                return this.citySubDivisionNameField;
            }
            set {
                this.citySubDivisionNameField = value;
            }
        }
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string MunicipalityCode {
            get {
                return this.municipalityCodeField;
            }
            set {
                this.municipalityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public LocationAddressMPAddressWashInstructions MPAddressWashInstructions {
            get {
                return this.mPAddressWashInstructionsField;
            }
            set {
                this.mPAddressWashInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public string DARReference {
            get {
                return this.dARReferenceField;
            }
            set {
                this.dARReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class LocationAddressMPAddressWashInstructions : MPAddressWashIstructionTypeCodeCodeType_000156 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class AssetTypeCodeType_DK0002 {
        
        private AssetTypeCodeType_DK0002ListIdentifier listIdentifierField;
        
        private AssetTypeCodeType_DK0002ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AssetTypeCodeType_DK0002ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AssetTypeCodeType_DK0002ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum AssetTypeCodeType_DK0002ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum AssetTypeCodeType_DK0002ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MPConnectionTypeCodeCodeType_000155 {
        
        private MPConnectionTypeCodeCodeType_000155ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MPConnectionTypeCodeCodeType_000155ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MPConnectionTypeCodeCodeType_000155ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MPConnectionTypeCodeCodeType_000155ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MPConnectionTypeCodeCodeType_000155ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MPConnectionTypeCodeCodeType_000155ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class DisconnectionTypeCodeType_000154 {
        
        private DisconnectionTypeCodeType_000154ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private DisconnectionTypeCodeType_000154ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DisconnectionTypeCodeType_000154ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DisconnectionTypeCodeType_000154ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum DisconnectionTypeCodeType_000154ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum DisconnectionTypeCodeType_000154ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class EnergyProductIdentificationCodeType_000120 {
        
        private EnergyProductIdentificationCodeType_000120ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private EnergyProductIdentificationCodeType_000120ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EnergyProductIdentificationCodeType_000120ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EnergyProductIdentificationCodeType_000120ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum EnergyProductIdentificationCodeType_000120ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum EnergyProductIdentificationCodeType_000120ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class ProductCharacteristic {
        
        private ProductCharacteristicIdentification identificationField;
        
        private ProductCharacteristicUnitType unitTypeField;
        
        /// <remarks/>
        public ProductCharacteristicIdentification Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public ProductCharacteristicUnitType UnitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class ProductCharacteristicIdentification : EnergyProductIdentificationCodeType_000120 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class ProductCharacteristicUnitType : MeasurementUnitCommonCodeType_000121 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class ContractedCapacityCharacteristics {
        
        private string maximumCurrentField;
        
        private string maximumPowerField;
        
        /// <remarks/>
        public string MaximumCurrent {
            get {
                return this.maximumCurrentField;
            }
            set {
                this.maximumCurrentField = value;
            }
        }
        
        /// <remarks/>
        public string MaximumPower {
            get {
                return this.maximumPowerField;
            }
            set {
                this.maximumPowerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointSubTypeCodeType_000153 {
        
        private MeteringPointSubTypeCodeType_000153ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MeteringPointSubTypeCodeType_000153ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeteringPointSubTypeCodeType_000153ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeteringPointSubTypeCodeType_000153ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MeteringPointSubTypeCodeType_000153ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MeteringPointSubTypeCodeType_000153ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointTypeCodeType_000138 {
        
        private MeteringPointTypeCodeType_000138ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MeteringPointTypeCodeType_000138ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeteringPointTypeCodeType_000138ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MeteringPointTypeCodeType_000138ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MeteringPointTypeCodeType_000138ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MeteringPointTypeCodeType_000138ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MPReadingCharacteristicsCodeType_DK0006 {
        
        private MPReadingCharacteristicsCodeType_DK0006ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private MPReadingCharacteristicsCodeType_DK0006ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MPReadingCharacteristicsCodeType_DK0006ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MPReadingCharacteristicsCodeType_DK0006ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MPReadingCharacteristicsCodeType_DK0006ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum MPReadingCharacteristicsCodeType_DK0006ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class PhysicalStatusCodeType_000141 {
        
        private PhysicalStatusCodeType_000141ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private PhysicalStatusCodeType_000141ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PhysicalStatusCodeType_000141ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PhysicalStatusCodeType_000141ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum PhysicalStatusCodeType_000141ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum PhysicalStatusCodeType_000141ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class SettlementMethodCodeType_000145 {
        
        private SettlementMethodCodeType_000145ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private SettlementMethodCodeType_000145ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SettlementMethodCodeType_000145ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SettlementMethodCodeType_000145ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum SettlementMethodCodeType_000145ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum SettlementMethodCodeType_000145ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristic {
        
        private MeteringPointCharacteristicSettlementMethod settlementMethodField;
        
        private MeteringPointCharacteristicPhysicalStatusOfMeteringPoint physicalStatusOfMeteringPointField;
        
        private string[] scheduledMeterReadingDateField;
        
        private MeteringPointCharacteristicMPReadingCharacteristics mPReadingCharacteristicsField;
        
        private MeteringPointCharacteristicTypeOfMeteringPoint typeOfMeteringPointField;
        
        private MeteringPointCharacteristicSubTypeOfMeteringPoint subTypeOfMeteringPointField;
        
        private string meterReadingOccurrenceField;
        
        private bool hourlyTimeSeriesField;
        
        private bool hourlyTimeSeriesFieldSpecified;
        
        private string netSettlementGroupField;
        
        private ContractedCapacityCharacteristics limitationContractedCapacityCharacteristicsField;
        
        private DomainLocation meteringGridAreaUsedDomainLocationField;
        
        private DomainLocation toGridDomainLocationField;
        
        private DomainLocation fromGridDomainLocationField;
        
        private bool productionObligationField;
        
        private bool productionObligationFieldSpecified;
        
        private DomainLocation powerPlantDomainLocationField;
        
        private string locationDescriptionField;
        
        private ProductCharacteristic includedProductCharacteristicField;
        
        private MeteringPointCharacteristicDisconnectionType disconnectionTypeField;
        
        private MeteringPointCharacteristicMPConnectionType mPConnectionTypeField;
        
        private string mPCapacityField;
        
        private MeteringPointCharacteristicAssetType assetTypeField;
        
        /// <remarks/>
        public MeteringPointCharacteristicSettlementMethod SettlementMethod {
            get {
                return this.settlementMethodField;
            }
            set {
                this.settlementMethodField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointCharacteristicPhysicalStatusOfMeteringPoint PhysicalStatusOfMeteringPoint {
            get {
                return this.physicalStatusOfMeteringPointField;
            }
            set {
                this.physicalStatusOfMeteringPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScheduledMeterReadingDate")]
        public string[] ScheduledMeterReadingDate {
            get {
                return this.scheduledMeterReadingDateField;
            }
            set {
                this.scheduledMeterReadingDateField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointCharacteristicMPReadingCharacteristics MPReadingCharacteristics {
            get {
                return this.mPReadingCharacteristicsField;
            }
            set {
                this.mPReadingCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointCharacteristicTypeOfMeteringPoint TypeOfMeteringPoint {
            get {
                return this.typeOfMeteringPointField;
            }
            set {
                this.typeOfMeteringPointField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointCharacteristicSubTypeOfMeteringPoint SubTypeOfMeteringPoint {
            get {
                return this.subTypeOfMeteringPointField;
            }
            set {
                this.subTypeOfMeteringPointField = value;
            }
        }
        
        /// <remarks/>
        public string MeterReadingOccurrence {
            get {
                return this.meterReadingOccurrenceField;
            }
            set {
                this.meterReadingOccurrenceField = value;
            }
        }
        
        /// <remarks/>
        public bool HourlyTimeSeries {
            get {
                return this.hourlyTimeSeriesField;
            }
            set {
                this.hourlyTimeSeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HourlyTimeSeriesSpecified {
            get {
                return this.hourlyTimeSeriesFieldSpecified;
            }
            set {
                this.hourlyTimeSeriesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NetSettlementGroup {
            get {
                return this.netSettlementGroupField;
            }
            set {
                this.netSettlementGroupField = value;
            }
        }
        
        /// <remarks/>
        public ContractedCapacityCharacteristics LimitationContractedCapacityCharacteristics {
            get {
                return this.limitationContractedCapacityCharacteristicsField;
            }
            set {
                this.limitationContractedCapacityCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public DomainLocation MeteringGridAreaUsedDomainLocation {
            get {
                return this.meteringGridAreaUsedDomainLocationField;
            }
            set {
                this.meteringGridAreaUsedDomainLocationField = value;
            }
        }
        
        /// <remarks/>
        public DomainLocation ToGridDomainLocation {
            get {
                return this.toGridDomainLocationField;
            }
            set {
                this.toGridDomainLocationField = value;
            }
        }
        
        /// <remarks/>
        public DomainLocation FromGridDomainLocation {
            get {
                return this.fromGridDomainLocationField;
            }
            set {
                this.fromGridDomainLocationField = value;
            }
        }
        
        /// <remarks/>
        public bool ProductionObligation {
            get {
                return this.productionObligationField;
            }
            set {
                this.productionObligationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductionObligationSpecified {
            get {
                return this.productionObligationFieldSpecified;
            }
            set {
                this.productionObligationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DomainLocation PowerPlantDomainLocation {
            get {
                return this.powerPlantDomainLocationField;
            }
            set {
                this.powerPlantDomainLocationField = value;
            }
        }
        
        /// <remarks/>
        public string LocationDescription {
            get {
                return this.locationDescriptionField;
            }
            set {
                this.locationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public ProductCharacteristic IncludedProductCharacteristic {
            get {
                return this.includedProductCharacteristicField;
            }
            set {
                this.includedProductCharacteristicField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointCharacteristicDisconnectionType DisconnectionType {
            get {
                return this.disconnectionTypeField;
            }
            set {
                this.disconnectionTypeField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointCharacteristicMPConnectionType MPConnectionType {
            get {
                return this.mPConnectionTypeField;
            }
            set {
                this.mPConnectionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MPCapacity {
            get {
                return this.mPCapacityField;
            }
            set {
                this.mPCapacityField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointCharacteristicAssetType AssetType {
            get {
                return this.assetTypeField;
            }
            set {
                this.assetTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristicSettlementMethod : SettlementMethodCodeType_000145 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristicPhysicalStatusOfMeteringPoint : PhysicalStatusCodeType_000141 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristicMPReadingCharacteristics : MPReadingCharacteristicsCodeType_DK0006 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristicTypeOfMeteringPoint : MeteringPointTypeCodeType_000138 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristicSubTypeOfMeteringPoint : MeteringPointSubTypeCodeType_000153 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristicDisconnectionType : DisconnectionTypeCodeType_000154 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristicMPConnectionType : MPConnectionTypeCodeCodeType_000155 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MeteringPointCharacteristicAssetType : AssetTypeCodeType_DK0002 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MasterDataMPEvent {
        
        private DomainLocation meteringPointDomainLocationField;
        
        private string identificationField;
        
        private MeteringPointCharacteristic detailMeteringPointCharacteristicField;
        
        private System.DateTime occurrenceField;
        
        private LocationAddress installationLocationAddressField;
        
        private MeterFacility meteringInstallationMeterFacilityField;
        
        private RelatedMeteringPoint parentRelatedMeteringPointField;
        
        private MeterCharacteristic meterInstallationMeterCharacteristicField;
        
        private MasterDataMPEventFunction functionField;
        
        /// <remarks/>
        public DomainLocation MeteringPointDomainLocation {
            get {
                return this.meteringPointDomainLocationField;
            }
            set {
                this.meteringPointDomainLocationField = value;
            }
        }
        
        /// <remarks/>
        public string Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public MeteringPointCharacteristic DetailMeteringPointCharacteristic {
            get {
                return this.detailMeteringPointCharacteristicField;
            }
            set {
                this.detailMeteringPointCharacteristicField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Occurrence {
            get {
                return this.occurrenceField;
            }
            set {
                this.occurrenceField = value;
            }
        }
        
        /// <remarks/>
        public LocationAddress InstallationLocationAddress {
            get {
                return this.installationLocationAddressField;
            }
            set {
                this.installationLocationAddressField = value;
            }
        }
        
        /// <remarks/>
        public MeterFacility MeteringInstallationMeterFacility {
            get {
                return this.meteringInstallationMeterFacilityField;
            }
            set {
                this.meteringInstallationMeterFacilityField = value;
            }
        }
        
        /// <remarks/>
        public RelatedMeteringPoint ParentRelatedMeteringPoint {
            get {
                return this.parentRelatedMeteringPointField;
            }
            set {
                this.parentRelatedMeteringPointField = value;
            }
        }
        
        /// <remarks/>
        public MeterCharacteristic MeterInstallationMeterCharacteristic {
            get {
                return this.meterInstallationMeterCharacteristicField;
            }
            set {
                this.meterInstallationMeterCharacteristicField = value;
            }
        }
        
        /// <remarks/>
        public MasterDataMPEventFunction Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class MasterDataMPEventFunction : DocumentFunctionCodeType_000118 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class SectorAreaIdentificationCodeType_000116 {
        
        private SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SectorAreaIdentificationCodeType_000116ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum SectorAreaIdentificationCodeType_000116ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class BusinessRoleCodeType_000113 {
        
        private BusinessRoleCodeType_000113ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessRoleCodeType_000113ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum BusinessRoleCodeType_000113ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum BusinessRoleCodeType_000113ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class BusinessReasonCodeType_000115 {
        
        private BusinessReasonCodeType_000115ListIdentifier listIdentifierField;
        
        private bool listIdentifierFieldSpecified;
        
        private BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListIdentifier listIdentifier {
            get {
                return this.listIdentifierField;
            }
            set {
                this.listIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool listIdentifierSpecified {
            get {
                return this.listIdentifierFieldSpecified;
            }
            set {
                this.listIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BusinessReasonCodeType_000115ListAgencyIdentifier listAgencyIdentifier {
            get {
                return this.listAgencyIdentifierField;
            }
            set {
                this.listAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum BusinessReasonCodeType_000115ListIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum BusinessReasonCodeType_000115ListAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class EnergyContext {
        
        private EnergyContextEnergyBusinessProcess energyBusinessProcessField;
        
        private EnergyContextEnergyBusinessProcessRole energyBusinessProcessRoleField;
        
        private EnergyContextEnergyIndustryClassification energyIndustryClassificationField;
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcess EnergyBusinessProcess {
            get {
                return this.energyBusinessProcessField;
            }
            set {
                this.energyBusinessProcessField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyBusinessProcessRole EnergyBusinessProcessRole {
            get {
                return this.energyBusinessProcessRoleField;
            }
            set {
                this.energyBusinessProcessRoleField = value;
            }
        }
        
        /// <remarks/>
        public EnergyContextEnergyIndustryClassification EnergyIndustryClassification {
            get {
                return this.energyIndustryClassificationField;
            }
            set {
                this.energyIndustryClassificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class EnergyContextEnergyBusinessProcess : BusinessReasonCodeType_000115 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class EnergyContextEnergyBusinessProcessRole : BusinessRoleCodeType_000113 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class EnergyContextEnergyIndustryClassification : SectorAreaIdentificationCodeType_000116 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class PartyIdentifierType_000112 {
        
        private PartyIdentifierType_000112SchemeIdentifier schemeIdentifierField;
        
        private bool schemeIdentifierFieldSpecified;
        
        private PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifierField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeIdentifier schemeIdentifier {
            get {
                return this.schemeIdentifierField;
            }
            set {
                this.schemeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schemeIdentifierSpecified {
            get {
                return this.schemeIdentifierFieldSpecified;
            }
            set {
                this.schemeIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PartyIdentifierType_000112SchemeAgencyIdentifier schemeAgencyIdentifier {
            get {
                return this.schemeAgencyIdentifierField;
            }
            set {
                this.schemeAgencyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum PartyIdentifierType_000112SchemeIdentifier {
        
        /// <remarks/>
        DK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public enum PartyIdentifierType_000112SchemeAgencyIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="un:unece:260:data:EEM-DK_RequestUpdateMasterDataMeteringPoint:v3")]
    public partial class EnergyParty {
        
        private PartyIdentifierType_000112 identificationField;
        
        /// <remarks/>
        public PartyIdentifierType_000112 Identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
    }
}
