// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IntegrationEvents/EnergySupplierChanged.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Energinet.DataHub.EnergySupplying.IntegrationEvents {

  /// <summary>Holder for reflection information generated from IntegrationEvents/EnergySupplierChanged.proto</summary>
  public static partial class EnergySupplierChangedReflection {

    #region Descriptor
    /// <summary>File descriptor for IntegrationEvents/EnergySupplierChanged.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnergySupplierChangedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1JbnRlZ3JhdGlvbkV2ZW50cy9FbmVyZ3lTdXBwbGllckNoYW5nZWQucHJv",
            "dG8ifQoVRW5lcmd5U3VwcGxpZXJDaGFuZ2VkEhoKEmFjY291bnRpbmdwb2lu",
            "dF9pZBgBIAEoCRITCgtnc3JuX251bWJlchgCIAEoCRIbChNlbmVyZ3lfc3Vw",
            "cGxpZXJfZ2xuGAMgASgJEhYKDmVmZmVjdGl2ZV9kYXRlGAQgASgJQjaqAjNF",
            "bmVyZ2luZXQuRGF0YUh1Yi5FbmVyZ3lTdXBwbHlpbmcuSW50ZWdyYXRpb25F",
            "dmVudHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Energinet.DataHub.EnergySupplying.IntegrationEvents.EnergySupplierChanged), global::Energinet.DataHub.EnergySupplying.IntegrationEvents.EnergySupplierChanged.Parser, new[]{ "AccountingpointId", "GsrnNumber", "EnergySupplierGln", "EffectiveDate" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EnergySupplierChanged : pb::IMessage<EnergySupplierChanged>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EnergySupplierChanged> _parser = new pb::MessageParser<EnergySupplierChanged>(() => new EnergySupplierChanged());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EnergySupplierChanged> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Energinet.DataHub.EnergySupplying.IntegrationEvents.EnergySupplierChangedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnergySupplierChanged() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnergySupplierChanged(EnergySupplierChanged other) : this() {
      accountingpointId_ = other.accountingpointId_;
      gsrnNumber_ = other.gsrnNumber_;
      energySupplierGln_ = other.energySupplierGln_;
      effectiveDate_ = other.effectiveDate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnergySupplierChanged Clone() {
      return new EnergySupplierChanged(this);
    }

    /// <summary>Field number for the "accountingpoint_id" field.</summary>
    public const int AccountingpointIdFieldNumber = 1;
    private string accountingpointId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountingpointId {
      get { return accountingpointId_; }
      set {
        accountingpointId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gsrn_number" field.</summary>
    public const int GsrnNumberFieldNumber = 2;
    private string gsrnNumber_ = "";
    /// <summary>
    /// Unique metering point identification
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GsrnNumber {
      get { return gsrnNumber_; }
      set {
        gsrnNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "energy_supplier_gln" field.</summary>
    public const int EnergySupplierGlnFieldNumber = 3;
    private string energySupplierGln_ = "";
    /// <summary>
    /// Unique Energy Supplier identifcation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EnergySupplierGln {
      get { return energySupplierGln_; }
      set {
        energySupplierGln_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "effective_date" field.</summary>
    public const int EffectiveDateFieldNumber = 4;
    private string effectiveDate_ = "";
    /// <summary>
    /// Date which the change of supplier goes into effect.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EffectiveDate {
      get { return effectiveDate_; }
      set {
        effectiveDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EnergySupplierChanged);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EnergySupplierChanged other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountingpointId != other.AccountingpointId) return false;
      if (GsrnNumber != other.GsrnNumber) return false;
      if (EnergySupplierGln != other.EnergySupplierGln) return false;
      if (EffectiveDate != other.EffectiveDate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountingpointId.Length != 0) hash ^= AccountingpointId.GetHashCode();
      if (GsrnNumber.Length != 0) hash ^= GsrnNumber.GetHashCode();
      if (EnergySupplierGln.Length != 0) hash ^= EnergySupplierGln.GetHashCode();
      if (EffectiveDate.Length != 0) hash ^= EffectiveDate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountingpointId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountingpointId);
      }
      if (GsrnNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GsrnNumber);
      }
      if (EnergySupplierGln.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EnergySupplierGln);
      }
      if (EffectiveDate.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(EffectiveDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountingpointId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountingpointId);
      }
      if (GsrnNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GsrnNumber);
      }
      if (EnergySupplierGln.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EnergySupplierGln);
      }
      if (EffectiveDate.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(EffectiveDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountingpointId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountingpointId);
      }
      if (GsrnNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GsrnNumber);
      }
      if (EnergySupplierGln.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EnergySupplierGln);
      }
      if (EffectiveDate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EffectiveDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EnergySupplierChanged other) {
      if (other == null) {
        return;
      }
      if (other.AccountingpointId.Length != 0) {
        AccountingpointId = other.AccountingpointId;
      }
      if (other.GsrnNumber.Length != 0) {
        GsrnNumber = other.GsrnNumber;
      }
      if (other.EnergySupplierGln.Length != 0) {
        EnergySupplierGln = other.EnergySupplierGln;
      }
      if (other.EffectiveDate.Length != 0) {
        EffectiveDate = other.EffectiveDate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AccountingpointId = input.ReadString();
            break;
          }
          case 18: {
            GsrnNumber = input.ReadString();
            break;
          }
          case 26: {
            EnergySupplierGln = input.ReadString();
            break;
          }
          case 34: {
            EffectiveDate = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AccountingpointId = input.ReadString();
            break;
          }
          case 18: {
            GsrnNumber = input.ReadString();
            break;
          }
          case 26: {
            EnergySupplierGln = input.ReadString();
            break;
          }
          case 34: {
            EffectiveDate = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
