name: 'Applying market roles migrations'
description: 'Applies migrations to the market roles DB to make sure the DB is up to date.'
inputs:
  kv_market_roles_name:
    description: 'Name of the keyvault to retrieve secrets from'
    required: true
  kv_market_roles_db_connection_string_secret_name:
    description: 'Name of the secret that contains the connection string for the database'
    required: true
  csproj_file_path:
    description: 'Path to the csproj file.'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Obtain keyvault information
      run: |
        keyvault_secret_details=$(az keyvault secret show --name "${{ inputs.kv_market_roles_db_connection_string_secret_name }}" --vault-name ${{ inputs.kv_market_roles_name }})
        echo $keyvault_secret_details
        market_roles_connection_string=$(echo $keyvault_secret_details | python -c "import sys, json; print(json.load(sys.stdin)['value'])")
        echo ::add-mask::$market_roles_connection_string
        dotnet run --project ${{ inputs.csproj_file_path }} --configuration Release -- "$market_roles_connection_string"
      shell: bash
