name: Render C4 models with Structurizr

on:
  workflow_call: {}

jobs:
  render_c4:
    uses: Energinet-DataHub/.github/.github/workflows/structurizr.yml@v10
    with:
      dsl: docs/diagrams/edi.dsl
    secrets: inherit
